spring:
  redis:
    host: localhost
    port: 8989

ustawienia:
  numerIndeksu: 439655
  wycena: "CENY_BEZ_ZMIAN"
  zamowienia: "POJEDYNCZE"
  zaopatrzenie: "POJEDYNCZE"
  wydarzenia: "INWENTARYZACJA"
  liczbaZadan: 200
